title: Code Examples
relative_links:
  enabled:     true
  collections: true
remote_theme:  "pmarsceill/just-the-docs"
aux_links:
  "Ansible Examples": "https://github.com/kathuriaas/ansible-examples.git"
  "Visit the repo on GitHub": "//github.com/kathuriaas/kathuriaas.github.io"
aux_links_new_tab: true
